// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.2
// source: command/paystore.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Paystore_CreateBalance_FullMethodName = "/paystore.Paystore/CreateBalance"
)

// PaystoreClient is the client API for Paystore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaystoreClient interface {
	CreateBalance(ctx context.Context, in *CreateBalanceRequest, opts ...grpc.CallOption) (*ReqeustResponse, error)
}

type paystoreClient struct {
	cc grpc.ClientConnInterface
}

func NewPaystoreClient(cc grpc.ClientConnInterface) PaystoreClient {
	return &paystoreClient{cc}
}

func (c *paystoreClient) CreateBalance(ctx context.Context, in *CreateBalanceRequest, opts ...grpc.CallOption) (*ReqeustResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReqeustResponse)
	err := c.cc.Invoke(ctx, Paystore_CreateBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaystoreServer is the server API for Paystore service.
// All implementations must embed UnimplementedPaystoreServer
// for forward compatibility.
type PaystoreServer interface {
	CreateBalance(context.Context, *CreateBalanceRequest) (*ReqeustResponse, error)
	mustEmbedUnimplementedPaystoreServer()
}

// UnimplementedPaystoreServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaystoreServer struct{}

func (UnimplementedPaystoreServer) CreateBalance(context.Context, *CreateBalanceRequest) (*ReqeustResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBalance not implemented")
}
func (UnimplementedPaystoreServer) mustEmbedUnimplementedPaystoreServer() {}
func (UnimplementedPaystoreServer) testEmbeddedByValue()                  {}

// UnsafePaystoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaystoreServer will
// result in compilation errors.
type UnsafePaystoreServer interface {
	mustEmbedUnimplementedPaystoreServer()
}

func RegisterPaystoreServer(s grpc.ServiceRegistrar, srv PaystoreServer) {
	// If the following call pancis, it indicates UnimplementedPaystoreServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Paystore_ServiceDesc, srv)
}

func _Paystore_CreateBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaystoreServer).CreateBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paystore_CreateBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaystoreServer).CreateBalance(ctx, req.(*CreateBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Paystore_ServiceDesc is the grpc.ServiceDesc for Paystore service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Paystore_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "paystore.Paystore",
	HandlerType: (*PaystoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBalance",
			Handler:    _Paystore_CreateBalance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "command/paystore.proto",
}
