// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.2
// source: command/paystore.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_SUCCES Status = 0
	Status_FAIL   Status = 1
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "SUCCES",
		1: "FAIL",
	}
	Status_value = map[string]int32{
		"SUCCES": 0,
		"FAIL":   1,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_command_paystore_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_command_paystore_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_command_paystore_proto_rawDescGZIP(), []int{0}
}

type CreateBalanceRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OwnerID          string                 `protobuf:"bytes,1,opt,name=OwnerID,proto3" json:"OwnerID,omitempty"`
	OrganizationSlug string                 `protobuf:"bytes,2,opt,name=OrganizationSlug,proto3" json:"OrganizationSlug,omitempty"`
	Currency         string                 `protobuf:"bytes,3,opt,name=Currency,proto3" json:"Currency,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateBalanceRequest) Reset() {
	*x = CreateBalanceRequest{}
	mi := &file_command_paystore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBalanceRequest) ProtoMessage() {}

func (x *CreateBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_command_paystore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBalanceRequest.ProtoReflect.Descriptor instead.
func (*CreateBalanceRequest) Descriptor() ([]byte, []int) {
	return file_command_paystore_proto_rawDescGZIP(), []int{0}
}

func (x *CreateBalanceRequest) GetOwnerID() string {
	if x != nil {
		return x.OwnerID
	}
	return ""
}

func (x *CreateBalanceRequest) GetOrganizationSlug() string {
	if x != nil {
		return x.OrganizationSlug
	}
	return ""
}

func (x *CreateBalanceRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type ReqeustResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Status        Status                 `protobuf:"varint,2,opt,name=status,proto3,enum=paystore.Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqeustResponse) Reset() {
	*x = ReqeustResponse{}
	mi := &file_command_paystore_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqeustResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqeustResponse) ProtoMessage() {}

func (x *ReqeustResponse) ProtoReflect() protoreflect.Message {
	mi := &file_command_paystore_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqeustResponse.ProtoReflect.Descriptor instead.
func (*ReqeustResponse) Descriptor() ([]byte, []int) {
	return file_command_paystore_proto_rawDescGZIP(), []int{1}
}

func (x *ReqeustResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *ReqeustResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_SUCCES
}

var File_command_paystore_proto protoreflect.FileDescriptor

const file_command_paystore_proto_rawDesc = "" +
	"\n" +
	"\x16command/paystore.proto\x12\bpaystore\"x\n" +
	"\x14CreateBalanceRequest\x12\x18\n" +
	"\aOwnerID\x18\x01 \x01(\tR\aOwnerID\x12*\n" +
	"\x10OrganizationSlug\x18\x02 \x01(\tR\x10OrganizationSlug\x12\x1a\n" +
	"\bCurrency\x18\x03 \x01(\tR\bCurrency\"K\n" +
	"\x0fReqeustResponse\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12(\n" +
	"\x06status\x18\x02 \x01(\x0e2\x10.paystore.StatusR\x06status*\x1e\n" +
	"\x06Status\x12\n" +
	"\n" +
	"\x06SUCCES\x10\x00\x12\b\n" +
	"\x04FAIL\x10\x012V\n" +
	"\bPaystore\x12J\n" +
	"\rCreateBalance\x12\x1e.paystore.CreateBalanceRequest\x1a\x19.paystore.ReqeustResponseB\n" +
	"Z\b./protosb\x06proto3"

var (
	file_command_paystore_proto_rawDescOnce sync.Once
	file_command_paystore_proto_rawDescData []byte
)

func file_command_paystore_proto_rawDescGZIP() []byte {
	file_command_paystore_proto_rawDescOnce.Do(func() {
		file_command_paystore_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_command_paystore_proto_rawDesc), len(file_command_paystore_proto_rawDesc)))
	})
	return file_command_paystore_proto_rawDescData
}

var file_command_paystore_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_command_paystore_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_command_paystore_proto_goTypes = []any{
	(Status)(0),                  // 0: paystore.Status
	(*CreateBalanceRequest)(nil), // 1: paystore.CreateBalanceRequest
	(*ReqeustResponse)(nil),      // 2: paystore.ReqeustResponse
}
var file_command_paystore_proto_depIdxs = []int32{
	0, // 0: paystore.ReqeustResponse.status:type_name -> paystore.Status
	1, // 1: paystore.Paystore.CreateBalance:input_type -> paystore.CreateBalanceRequest
	2, // 2: paystore.Paystore.CreateBalance:output_type -> paystore.ReqeustResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_command_paystore_proto_init() }
func file_command_paystore_proto_init() {
	if File_command_paystore_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_command_paystore_proto_rawDesc), len(file_command_paystore_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_command_paystore_proto_goTypes,
		DependencyIndexes: file_command_paystore_proto_depIdxs,
		EnumInfos:         file_command_paystore_proto_enumTypes,
		MessageInfos:      file_command_paystore_proto_msgTypes,
	}.Build()
	File_command_paystore_proto = out.File
	file_command_paystore_proto_goTypes = nil
	file_command_paystore_proto_depIdxs = nil
}
