// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.2
// source: operation/paystore.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentStatus int32

const (
	PaymentStatus_PAYMENT_STATUS_UNSPECIFIED PaymentStatus = 0 // Required by protobuf style guide
	PaymentStatus_PAYMENT_STATUS_PENDING     PaymentStatus = 1
	PaymentStatus_PAYMENT_STATUS_PAID        PaymentStatus = 2
	PaymentStatus_PAYMENT_STATUS_FAILED      PaymentStatus = 3
)

// Enum value maps for PaymentStatus.
var (
	PaymentStatus_name = map[int32]string{
		0: "PAYMENT_STATUS_UNSPECIFIED",
		1: "PAYMENT_STATUS_PENDING",
		2: "PAYMENT_STATUS_PAID",
		3: "PAYMENT_STATUS_FAILED",
	}
	PaymentStatus_value = map[string]int32{
		"PAYMENT_STATUS_UNSPECIFIED": 0,
		"PAYMENT_STATUS_PENDING":     1,
		"PAYMENT_STATUS_PAID":        2,
		"PAYMENT_STATUS_FAILED":      3,
	}
)

func (x PaymentStatus) Enum() *PaymentStatus {
	p := new(PaymentStatus)
	*p = x
	return p
}

func (x PaymentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_operation_paystore_proto_enumTypes[0].Descriptor()
}

func (PaymentStatus) Type() protoreflect.EnumType {
	return &file_operation_paystore_proto_enumTypes[0]
}

func (x PaymentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentStatus.Descriptor instead.
func (PaymentStatus) EnumDescriptor() ([]byte, []int) {
	return file_operation_paystore_proto_rawDescGZIP(), []int{0}
}

type CreateBalanceRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ExternalID       string                 `protobuf:"bytes,1,opt,name=ExternalID,proto3" json:"ExternalID,omitempty"`
	OrganizationSlug string                 `protobuf:"bytes,2,opt,name=OrganizationSlug,proto3" json:"OrganizationSlug,omitempty"`
	Currency         string                 `protobuf:"bytes,3,opt,name=Currency,proto3" json:"Currency,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateBalanceRequest) Reset() {
	*x = CreateBalanceRequest{}
	mi := &file_operation_paystore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBalanceRequest) ProtoMessage() {}

func (x *CreateBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_operation_paystore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBalanceRequest.ProtoReflect.Descriptor instead.
func (*CreateBalanceRequest) Descriptor() ([]byte, []int) {
	return file_operation_paystore_proto_rawDescGZIP(), []int{0}
}

func (x *CreateBalanceRequest) GetExternalID() string {
	if x != nil {
		return x.ExternalID
	}
	return ""
}

func (x *CreateBalanceRequest) GetOrganizationSlug() string {
	if x != nil {
		return x.OrganizationSlug
	}
	return ""
}

func (x *CreateBalanceRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type CreatePaymentRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AccountUUID    string                 `protobuf:"bytes,1,opt,name=AccountUUID,proto3" json:"AccountUUID,omitempty"`
	Amount         int64                  `protobuf:"varint,2,opt,name=Amount,proto3" json:"Amount,omitempty"`
	VendorRecordId string                 `protobuf:"bytes,3,opt,name=VendorRecordId,proto3" json:"VendorRecordId,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreatePaymentRequest) Reset() {
	*x = CreatePaymentRequest{}
	mi := &file_operation_paystore_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentRequest) ProtoMessage() {}

func (x *CreatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_operation_paystore_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_operation_paystore_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePaymentRequest) GetAccountUUID() string {
	if x != nil {
		return x.AccountUUID
	}
	return ""
}

func (x *CreatePaymentRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreatePaymentRequest) GetVendorRecordId() string {
	if x != nil {
		return x.VendorRecordId
	}
	return ""
}

type FinalizedPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountUUID   string                 `protobuf:"bytes,1,opt,name=AccountUUID,proto3" json:"AccountUUID,omitempty"`
	PaymentUUID   string                 `protobuf:"bytes,2,opt,name=PaymentUUID,proto3" json:"PaymentUUID,omitempty"`
	PaymentStatus PaymentStatus          `protobuf:"varint,3,opt,name=PaymentStatus,proto3,enum=paystore.PaymentStatus" json:"PaymentStatus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizedPaymentRequest) Reset() {
	*x = FinalizedPaymentRequest{}
	mi := &file_operation_paystore_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizedPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizedPaymentRequest) ProtoMessage() {}

func (x *FinalizedPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_operation_paystore_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizedPaymentRequest.ProtoReflect.Descriptor instead.
func (*FinalizedPaymentRequest) Descriptor() ([]byte, []int) {
	return file_operation_paystore_proto_rawDescGZIP(), []int{2}
}

func (x *FinalizedPaymentRequest) GetAccountUUID() string {
	if x != nil {
		return x.AccountUUID
	}
	return ""
}

func (x *FinalizedPaymentRequest) GetPaymentUUID() string {
	if x != nil {
		return x.PaymentUUID
	}
	return ""
}

func (x *FinalizedPaymentRequest) GetPaymentStatus() PaymentStatus {
	if x != nil {
		return x.PaymentStatus
	}
	return PaymentStatus_PAYMENT_STATUS_UNSPECIFIED
}

type CreateWithdrawRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AccountUUID    string                 `protobuf:"bytes,1,opt,name=AccountUUID,proto3" json:"AccountUUID,omitempty"`
	Amount         int64                  `protobuf:"varint,2,opt,name=Amount,proto3" json:"Amount,omitempty"`
	VendorRecordId string                 `protobuf:"bytes,3,opt,name=VendorRecordId,proto3" json:"VendorRecordId,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateWithdrawRequest) Reset() {
	*x = CreateWithdrawRequest{}
	mi := &file_operation_paystore_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWithdrawRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWithdrawRequest) ProtoMessage() {}

func (x *CreateWithdrawRequest) ProtoReflect() protoreflect.Message {
	mi := &file_operation_paystore_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWithdrawRequest.ProtoReflect.Descriptor instead.
func (*CreateWithdrawRequest) Descriptor() ([]byte, []int) {
	return file_operation_paystore_proto_rawDescGZIP(), []int{3}
}

func (x *CreateWithdrawRequest) GetAccountUUID() string {
	if x != nil {
		return x.AccountUUID
	}
	return ""
}

func (x *CreateWithdrawRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateWithdrawRequest) GetVendorRecordId() string {
	if x != nil {
		return x.VendorRecordId
	}
	return ""
}

type FinalizedWithdrawRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AccountUUId    string                 `protobuf:"bytes,1,opt,name=AccountUUId,proto3" json:"AccountUUId,omitempty"`
	WithdrawUUID   string                 `protobuf:"bytes,2,opt,name=WithdrawUUID,proto3" json:"WithdrawUUID,omitempty"`
	WithdrawStatus PaymentStatus          `protobuf:"varint,3,opt,name=WithdrawStatus,proto3,enum=paystore.PaymentStatus" json:"WithdrawStatus,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FinalizedWithdrawRequest) Reset() {
	*x = FinalizedWithdrawRequest{}
	mi := &file_operation_paystore_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizedWithdrawRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizedWithdrawRequest) ProtoMessage() {}

func (x *FinalizedWithdrawRequest) ProtoReflect() protoreflect.Message {
	mi := &file_operation_paystore_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizedWithdrawRequest.ProtoReflect.Descriptor instead.
func (*FinalizedWithdrawRequest) Descriptor() ([]byte, []int) {
	return file_operation_paystore_proto_rawDescGZIP(), []int{4}
}

func (x *FinalizedWithdrawRequest) GetAccountUUId() string {
	if x != nil {
		return x.AccountUUId
	}
	return ""
}

func (x *FinalizedWithdrawRequest) GetWithdrawUUID() string {
	if x != nil {
		return x.WithdrawUUID
	}
	return ""
}

func (x *FinalizedWithdrawRequest) GetWithdrawStatus() PaymentStatus {
	if x != nil {
		return x.WithdrawStatus
	}
	return PaymentStatus_PAYMENT_STATUS_UNSPECIFIED
}

type CreatedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatedResponse) Reset() {
	*x = CreatedResponse{}
	mi := &file_operation_paystore_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatedResponse) ProtoMessage() {}

func (x *CreatedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_operation_paystore_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatedResponse.ProtoReflect.Descriptor instead.
func (*CreatedResponse) Descriptor() ([]byte, []int) {
	return file_operation_paystore_proto_rawDescGZIP(), []int{5}
}

func (x *CreatedResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type EmptyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyResponse) Reset() {
	*x = EmptyResponse{}
	mi := &file_operation_paystore_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyResponse) ProtoMessage() {}

func (x *EmptyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_operation_paystore_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyResponse.ProtoReflect.Descriptor instead.
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return file_operation_paystore_proto_rawDescGZIP(), []int{6}
}

var File_operation_paystore_proto protoreflect.FileDescriptor

const file_operation_paystore_proto_rawDesc = "" +
	"\n" +
	"\x18operation/paystore.proto\x12\bpaystore\"~\n" +
	"\x14CreateBalanceRequest\x12\x1e\n" +
	"\n" +
	"ExternalID\x18\x01 \x01(\tR\n" +
	"ExternalID\x12*\n" +
	"\x10OrganizationSlug\x18\x02 \x01(\tR\x10OrganizationSlug\x12\x1a\n" +
	"\bCurrency\x18\x03 \x01(\tR\bCurrency\"x\n" +
	"\x14CreatePaymentRequest\x12 \n" +
	"\vAccountUUID\x18\x01 \x01(\tR\vAccountUUID\x12\x16\n" +
	"\x06Amount\x18\x02 \x01(\x03R\x06Amount\x12&\n" +
	"\x0eVendorRecordId\x18\x03 \x01(\tR\x0eVendorRecordId\"\x9c\x01\n" +
	"\x17FinalizedPaymentRequest\x12 \n" +
	"\vAccountUUID\x18\x01 \x01(\tR\vAccountUUID\x12 \n" +
	"\vPaymentUUID\x18\x02 \x01(\tR\vPaymentUUID\x12=\n" +
	"\rPaymentStatus\x18\x03 \x01(\x0e2\x17.paystore.PaymentStatusR\rPaymentStatus\"y\n" +
	"\x15CreateWithdrawRequest\x12 \n" +
	"\vAccountUUID\x18\x01 \x01(\tR\vAccountUUID\x12\x16\n" +
	"\x06Amount\x18\x02 \x01(\x03R\x06Amount\x12&\n" +
	"\x0eVendorRecordId\x18\x03 \x01(\tR\x0eVendorRecordId\"\xa1\x01\n" +
	"\x18FinalizedWithdrawRequest\x12 \n" +
	"\vAccountUUId\x18\x01 \x01(\tR\vAccountUUId\x12\"\n" +
	"\fWithdrawUUID\x18\x02 \x01(\tR\fWithdrawUUID\x12?\n" +
	"\x0eWithdrawStatus\x18\x03 \x01(\x0e2\x17.paystore.PaymentStatusR\x0eWithdrawStatus\"!\n" +
	"\x0fCreatedResponse\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\"\x0f\n" +
	"\rEmptyResponse*\x7f\n" +
	"\rPaymentStatus\x12\x1e\n" +
	"\x1aPAYMENT_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PAYMENT_STATUS_PENDING\x10\x01\x12\x17\n" +
	"\x13PAYMENT_STATUS_PAID\x10\x02\x12\x19\n" +
	"\x15PAYMENT_STATUS_FAILED\x10\x032\x92\x03\n" +
	"\bPaystore\x12J\n" +
	"\rCreateBalance\x12\x1e.paystore.CreateBalanceRequest\x1a\x19.paystore.CreatedResponse\x12J\n" +
	"\rCreatePayment\x12\x1e.paystore.CreatePaymentRequest\x1a\x19.paystore.CreatedResponse\x12N\n" +
	"\x10FinalizedPayment\x12!.paystore.FinalizedPaymentRequest\x1a\x17.paystore.EmptyResponse\x12L\n" +
	"\x0eCreateWithdraw\x12\x1f.paystore.CreateWithdrawRequest\x1a\x19.paystore.CreatedResponse\x12P\n" +
	"\x11FinalizedWithdraw\x12\".paystore.FinalizedWithdrawRequest\x1a\x17.paystore.EmptyResponseB\n" +
	"Z\b./protosb\x06proto3"

var (
	file_operation_paystore_proto_rawDescOnce sync.Once
	file_operation_paystore_proto_rawDescData []byte
)

func file_operation_paystore_proto_rawDescGZIP() []byte {
	file_operation_paystore_proto_rawDescOnce.Do(func() {
		file_operation_paystore_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_operation_paystore_proto_rawDesc), len(file_operation_paystore_proto_rawDesc)))
	})
	return file_operation_paystore_proto_rawDescData
}

var file_operation_paystore_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_operation_paystore_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_operation_paystore_proto_goTypes = []any{
	(PaymentStatus)(0),               // 0: paystore.PaymentStatus
	(*CreateBalanceRequest)(nil),     // 1: paystore.CreateBalanceRequest
	(*CreatePaymentRequest)(nil),     // 2: paystore.CreatePaymentRequest
	(*FinalizedPaymentRequest)(nil),  // 3: paystore.FinalizedPaymentRequest
	(*CreateWithdrawRequest)(nil),    // 4: paystore.CreateWithdrawRequest
	(*FinalizedWithdrawRequest)(nil), // 5: paystore.FinalizedWithdrawRequest
	(*CreatedResponse)(nil),          // 6: paystore.CreatedResponse
	(*EmptyResponse)(nil),            // 7: paystore.EmptyResponse
}
var file_operation_paystore_proto_depIdxs = []int32{
	0, // 0: paystore.FinalizedPaymentRequest.PaymentStatus:type_name -> paystore.PaymentStatus
	0, // 1: paystore.FinalizedWithdrawRequest.WithdrawStatus:type_name -> paystore.PaymentStatus
	1, // 2: paystore.Paystore.CreateBalance:input_type -> paystore.CreateBalanceRequest
	2, // 3: paystore.Paystore.CreatePayment:input_type -> paystore.CreatePaymentRequest
	3, // 4: paystore.Paystore.FinalizedPayment:input_type -> paystore.FinalizedPaymentRequest
	4, // 5: paystore.Paystore.CreateWithdraw:input_type -> paystore.CreateWithdrawRequest
	5, // 6: paystore.Paystore.FinalizedWithdraw:input_type -> paystore.FinalizedWithdrawRequest
	6, // 7: paystore.Paystore.CreateBalance:output_type -> paystore.CreatedResponse
	6, // 8: paystore.Paystore.CreatePayment:output_type -> paystore.CreatedResponse
	7, // 9: paystore.Paystore.FinalizedPayment:output_type -> paystore.EmptyResponse
	6, // 10: paystore.Paystore.CreateWithdraw:output_type -> paystore.CreatedResponse
	7, // 11: paystore.Paystore.FinalizedWithdraw:output_type -> paystore.EmptyResponse
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_operation_paystore_proto_init() }
func file_operation_paystore_proto_init() {
	if File_operation_paystore_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_operation_paystore_proto_rawDesc), len(file_operation_paystore_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_operation_paystore_proto_goTypes,
		DependencyIndexes: file_operation_paystore_proto_depIdxs,
		EnumInfos:         file_operation_paystore_proto_enumTypes,
		MessageInfos:      file_operation_paystore_proto_msgTypes,
	}.Build()
	File_operation_paystore_proto = out.File
	file_operation_paystore_proto_goTypes = nil
	file_operation_paystore_proto_depIdxs = nil
}
